### ISSUE TITLE
Upload to CPAN and mimimi

### ISSUE THREAD

**Issue by konsumate** [PerlDancer/Dancer2-Plugin-Auth-Extensible-Provider-LDAP#2]
Hey there,

First, thanks for your OpenLdap Provider. You beat me to the openldap implementation by 1 day. I finished mine yesterday and wanted to create a pull request as of today for this one. Reviewed your code and it seems legit.
1. Could you please add this package to CPAN? Thanks! 
2. A small differences I've found:
   You were using `$self->plugin->app->log` to log messages, where I used `$self->plugin->dsl->error/warning/debug/info` - I'm not sure which one is correct.
3. Installed & verified against my OpenLdap installation. Works!

Thanks for your commitment!

**Comment by SysPete** [comment]
Hi @corecache 

Apologies for slow response. LDAP provider has been uploaded to CPAN though you need latest version to avoid possible test failures.

I use `$self->plugin->app->log` since earlier versions of the new Plugin2-based `Dancer2::Plugin` didn't give you access to `dsl`. Nothing wrong with the way you were doing it as long as you make sure you set your D2 min version dep to 0.202000.

Good to know you have it working - I haven't had chance to make use of it myself yet.

Closing issue as I think we're all done.
